const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');
const Heyna = require('./HeynaReporter');

const BRAND = {
    name: 'HEYNA REPORT',
    tagline: 'From Execution to Evidence.',
    subtitle: 'Enterprise QA Automation Reporting Framework',
    footer: 'Generated by Playwright Automation Framework'
};

const PAGE = {
    margin: 48,
    bottom: 82,
    width: 595.28,
    height: 841.89
};

const COLORS = {
    navy: '#123A63',
    navyDark: '#0B2A47',
    green: '#16A05D',
    red: '#D32F2F',
    orange: '#F59E0B',
    blue: '#2563EB',
    black: '#1F2937',
    gray: '#6B7280',
    lightGray: '#F8FAFC',
    midGray: '#E5E7EB',
    white: '#FFFFFF'
};

class HeynaPdfGenerator {
    static async generate(options = {}) {
        return new Promise((resolve, reject) => {
            const reportDir = path.join(process.cwd(), 'reports');
            fs.mkdirSync(reportDir, { recursive: true });

            const outputPath = options.outputPath || path.join(reportDir, 'HeynaReport.pdf');
            const legacyPath = path.join(reportDir, 'TestExecutionReport.pdf');
            const doc = new PDFDocument({
                size: 'A4',
                margin: PAGE.margin,
                autoFirstPage: true,
                bufferPages: true,
                info: {
                    Title: 'HEYNA REPORT v2.0',
                    Author: 'Playwright Automation Framework',
                    Subject: BRAND.subtitle
                }
            });
            const stream = fs.createWriteStream(outputPath);

            doc.pipe(stream);

            try {
                const summary = Heyna.getSummary();
                const executionData = Heyna.getExecutionData();
                const failedTests = executionData.filter(tc => this.normalizeStatus(tc.status) === 'FAILED');

                this.cover(doc, summary, options);
                doc.addPage();
                this.executionSummary(doc, summary);
                this.testCaseSummary(doc, executionData);
                this.failedTestAnalysis(doc, failedTests);

                executionData.forEach((testCase, index) => {
                    doc.addPage();
                    this.testCaseDetail(doc, testCase, index + 1);
                });

                const contentPageCount = this.pageCount(doc);
                this.footer(doc, contentPageCount);
                this.validatePageCount(doc, contentPageCount);
                doc.end();
            } catch (error) {
                reject(error);
            }

            stream.on('finish', () => {
                if (outputPath !== legacyPath) {
                    fs.copyFileSync(outputPath, legacyPath);
                }
                resolve(outputPath);
            });
            stream.on('error', reject);
        });
    }

    static cover(doc, summary, options = {}) {
        const contentWidth = this.contentWidth(doc);
        const logoPath = this.logoPath(options.logoPath);

        doc.y = 74;
        if (logoPath) {
            this.centerImage(doc, logoPath, 210, 150);
            doc.moveDown(0.7);
        } else {
            doc.font('Helvetica-Bold')
                .fontSize(28)
                .fillColor(COLORS.navy)
                .text(BRAND.name, PAGE.margin, doc.y, { width: contentWidth, align: 'center' });
            doc.moveDown(2);
        }

        doc.font('Helvetica-Bold')
            .fontSize(28)
            .fillColor(COLORS.navy)
            .text(BRAND.name, PAGE.margin, doc.y, { width: contentWidth, align: 'center' });
        doc.moveDown(0.35);
        doc.font('Helvetica')
            .fontSize(13)
            .fillColor(COLORS.gray)
            .text(BRAND.tagline, PAGE.margin, doc.y, { width: contentWidth, align: 'center' });

        doc.y = 312;
        this.divider(doc);
        doc.moveDown(1);

        this.infoGrid(doc, [
            ['Project', summary.project],
            ['Feature', summary.feature],
            ['Environment', summary.environment],
            ['Browser', summary.browser],
            ['Executed By', summary.executedBy],
            ['Execution Date', summary.executionDate]
        ], { x: 92, width: PAGE.width - 184 });

        doc.moveDown(1.2);
        this.divider(doc);
        doc.moveDown(1.1);

        this.sectionTitle(doc, 'EXECUTION SUMMARY', { align: 'center' });
        this.summaryCards(doc, summary);
    }

    static executionSummary(doc, summary) {
        this.sectionTitle(doc, 'EXECUTION SUMMARY');
        this.table(doc, [
            { label: 'Metric', width: 230 },
            { label: 'Value', width: 260 }
        ], [
            ['Total Tests', summary.total],
            ['Passed', summary.passed],
            ['Failed', summary.failed],
            ['Skipped', summary.skipped],
            ['Pass Rate', `${summary.passRate}%`],
            ['Total Duration', this.formatDuration(summary.totalDuration)]
        ], { statusColumn: 0 });
        doc.moveDown(1.4);
    }

    static testCaseSummary(doc, executionData) {
        this.sectionTitle(doc, 'TEST CASE SUMMARY');
        this.table(doc, [
            { label: 'Test Case', width: 310 },
            { label: 'Status', width: 105 },
            { label: 'Duration', width: 75 }
        ], executionData.map(tc => [
            tc.testCase,
            this.normalizeStatus(tc.status),
            this.formatDuration(tc.duration)
        ]), { statusColumn: 1 });
        doc.moveDown(1.2);
    }

    static failedTestAnalysis(doc, failedTests) {
        this.sectionTitle(doc, 'FAILED TEST ANALYSIS');

        if (!failedTests.length) {
            this.noteBox(doc, 'No failed test cases found.', COLORS.green);
            return;
        }

        failedTests.forEach((tc, index) => {
            if (index > 0) doc.moveDown(0.8);
            const failedStep = (tc.steps || []).find(step => this.normalizeStatus(step.status) === 'FAILED') || {};
            const screenshot = this.resolveScreenshot(failedStep.screenshot) || this.findLatestFailedScreenshot(tc.testCase);
            const desc = failedStep.name ? Heyna.getStepDescription(failedStep.name) : null;

            this.ensureSpace(doc, 174);
            const top = doc.y;
            const height = screenshot ? 430 : 174;

            doc.roundedRect(PAGE.margin, top, this.contentWidth(doc), height, 6)
                .lineWidth(1)
                .stroke(COLORS.midGray);
            doc.rect(PAGE.margin, top, this.contentWidth(doc), 34)
                .fillAndStroke(COLORS.lightGray, COLORS.midGray);
            doc.font('Helvetica-Bold').fontSize(12).fillColor(COLORS.red)
                .text(tc.testCase, PAGE.margin + 14, top + 11, { width: this.contentWidth(doc) - 28 });

            let y = top + 48;
            y = this.inlineField(doc, 'Failed Step', desc ? desc.stepName : failedStep.name || 'N/A', y);
            y = this.inlineField(doc, 'Error Message', failedStep.errorMessage || tc.errorMessage || 'N/A', y);
            y = this.inlineField(doc, 'Duration', this.formatDuration(tc.duration), y);

            doc.y = y + 8;
            if (screenshot) {
                this.image(doc, screenshot, { width: 470, height: 250, x: 62 });
            }

            doc.y = top + height + 16;
        });
    }

    static testCaseDetail(doc, tc, number) {
        this.sectionTitle(doc, `${number}. ${tc.testCase}`);
        this.inlineMeta(doc, [
            ['Status', this.normalizeStatus(tc.status)],
            ['Duration', this.formatDuration(tc.duration)],
            ['Feature', tc.feature || '-']
        ]);
        doc.moveDown(1);

        this.sectionTitle(doc, 'STEP SUMMARY');
        this.table(doc, [
            { label: 'No', width: 45 },
            { label: 'Step', width: 335 },
            { label: 'Result', width: 110 }
        ], (tc.steps || []).map((step, index) => [
            index + 1,
            Heyna.getStepDescription(step.name).stepName,
            this.normalizeStatus(step.status)
        ]), { statusColumn: 2 });

        doc.moveDown(0.8);
        (tc.steps || []).forEach((step, index) => this.evidenceCard(doc, step, index + 1));
        this.apiActivity(doc, tc.testCase);
    }

    static evidenceCard(doc, step, number) {
        const desc = Heyna.getStepDescription(step.name);
        const status = this.normalizeStatus(step.status);
        const screenshot = this.resolveScreenshot(step.screenshot);
        const actionText = step.action
            ? `Perform ${step.action} on ${step.target || 'element'}.`
            : desc.action;
        const expectedText = step.action
            ? `${desc.stepName} action completes successfully.`
            : desc.expectedResult;
        const cardHeight = 176;

        this.ensureSpace(doc, cardHeight + (screenshot ? 275 : 0));
        const top = doc.y;

        doc.roundedRect(PAGE.margin, top, this.contentWidth(doc), cardHeight, 6)
            .lineWidth(1)
            .stroke(COLORS.midGray);
        doc.rect(PAGE.margin, top, this.contentWidth(doc), 34)
            .fillAndStroke(COLORS.lightGray, COLORS.midGray);
        doc.font('Helvetica-Bold').fontSize(11).fillColor(COLORS.navy)
            .text(`Step Information ${number}`, PAGE.margin + 14, top + 11, { width: this.contentWidth(doc) - 28 });

        let y = top + 48;
        y = this.inlineField(doc, 'Step Name', desc.stepName, y);
        y = this.inlineField(doc, 'Action', actionText, y);
        y = this.inlineField(doc, 'Expected Result', expectedText, y);
        y = this.inlineField(doc, 'Actual Result', step.errorMessage || `${desc.stepName} ${status.toLowerCase()}.`, y);
        this.inlineField(doc, 'Result', status, y, this.statusColor(status));

        doc.y = top + cardHeight + 14;
        if (screenshot) {
            this.image(doc, screenshot, { width: 490, height: 270, x: PAGE.margin });
        }
        doc.moveDown(0.8);
    }

    static apiActivity(doc, testCase) {
        const file = path.join(process.cwd(), 'evidence', testCase, 'api-log.json');
        if (!fs.existsSync(file)) return;

        const logs = Heyna.filterApiLogs(JSON.parse(fs.readFileSync(file, 'utf8')));
        if (!logs.length) return;

        this.ensureSpace(doc, 120);
        this.sectionTitle(doc, 'API ACTIVITY');
        this.table(doc, [
            { label: 'Method', width: 70 },
            { label: 'Endpoint', width: 295 },
            { label: 'Status', width: 65 },
            { label: 'Time', width: 60 }
        ], logs.map(log => [
            log.method || 'N/A',
            Heyna.formatApiUrl(log.url),
            log.status || 'N/A',
            this.formatDuration(log.duration || 0)
        ]), { fontSize: 8, statusColumn: 2 });
    }

    static table(doc, columns, rows, options = {}) {
        const x = options.x || PAGE.margin;
        const width = columns.reduce((sum, column) => sum + column.width, 0);
        const fontSize = options.fontSize || 9;
        const headerHeight = 30;
        const minRowHeight = options.rowHeight || 30;

        this.ensureSpace(doc, headerHeight + minRowHeight);
        let y = doc.y;

        doc.lineWidth(0.8);
        let currentX = x;
        columns.forEach(column => {
            doc.rect(currentX, y, column.width, headerHeight)
                .fillAndStroke(COLORS.navy, COLORS.navy);
            doc.font('Helvetica-Bold')
                .fontSize(9)
                .fillColor(COLORS.white)
                .text(column.label, currentX + 8, y + 10, { width: column.width - 16, ellipsis: true });
            currentX += column.width;
        });
        y += headerHeight;

        if (!rows.length) {
            rows = [['No data available']];
            columns = [{ label: '', width }];
        }

        rows.forEach((row, rowIndex) => {
            const rowHeight = this.rowHeight(doc, columns, row, fontSize, minRowHeight);
            if (y + rowHeight > PAGE.height - PAGE.bottom) {
                doc.addPage();
                y = PAGE.margin;
                currentX = x;
                columns.forEach(column => {
                    doc.rect(currentX, y, column.width, headerHeight)
                        .fillAndStroke(COLORS.navy, COLORS.navy);
                    doc.font('Helvetica-Bold')
                        .fontSize(9)
                        .fillColor(COLORS.white)
                        .text(column.label, currentX + 8, y + 10, { width: column.width - 16, ellipsis: true });
                    currentX += column.width;
                });
                y += headerHeight;
            }

            currentX = x;
            columns.forEach((column, columnIndex) => {
                const rawValue = row[columnIndex] == null ? '' : row[columnIndex];
                const value = String(rawValue);
                const isStatus = columnIndex === options.statusColumn;

                doc.rect(currentX, y, column.width, rowHeight)
                    .fillAndStroke(rowIndex % 2 === 0 ? COLORS.white : COLORS.lightGray, COLORS.midGray);
                doc.font(isStatus ? 'Helvetica-Bold' : 'Helvetica')
                    .fontSize(fontSize)
                    .fillColor(isStatus ? this.statusColor(value) : COLORS.black)
                    .text(value, currentX + 8, y + 9, {
                        width: column.width - 16,
                        height: rowHeight - 12,
                        ellipsis: true
                    });
                currentX += column.width;
            });

            y += rowHeight;
        });

        doc.y = y + 18;
        doc.lineWidth(1).fillColor(COLORS.black);
    }

    static rowHeight(doc, columns, row, fontSize, minHeight) {
        const heights = columns.map((column, index) => {
            const value = String(row[index] == null ? '' : row[index]);
            return doc.heightOfString(value, {
                width: column.width - 16,
                fontSize
            }) + 18;
        });

        return Math.max(minHeight, Math.ceil(Math.max(...heights)));
    }

    static infoGrid(doc, rows, options = {}) {
        const x = options.x || PAGE.margin;
        const width = options.width || this.contentWidth(doc);
        const labelWidth = 142;
        const rowHeight = 30;
        let y = doc.y;

        rows.forEach(([label, value], index) => {
            const rowY = y + index * rowHeight;
            doc.rect(x, rowY, width, rowHeight).stroke(COLORS.midGray);
            doc.rect(x, rowY, labelWidth, rowHeight).fillAndStroke(COLORS.lightGray, COLORS.midGray);
            doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.gray)
                .text(label, x + 10, rowY + 10, { width: labelWidth - 20 });
            doc.font('Helvetica').fontSize(9).fillColor(COLORS.black)
                .text(String(value || '-'), x + labelWidth + 12, rowY + 10, { width: width - labelWidth - 24, ellipsis: true });
        });

        doc.y = y + rows.length * rowHeight;
    }

    static summaryCards(doc, summary) {
        const metrics = [
            ['Total Tests', summary.total, COLORS.blue],
            ['Passed', summary.passed, COLORS.green],
            ['Failed', summary.failed, COLORS.red],
            ['Skipped', summary.skipped, COLORS.orange],
            ['Pass Rate', `${summary.passRate}%`, COLORS.navy],
            ['Total Duration', this.formatDuration(summary.totalDuration), COLORS.navyDark]
        ];
        const gap = 10;
        const cardWidth = 78;
        const cardHeight = 56;
        const startX = (PAGE.width - ((cardWidth * metrics.length) + (gap * (metrics.length - 1)))) / 2;
        const y = doc.y;

        metrics.forEach(([label, value, color], index) => {
            const x = startX + index * (cardWidth + gap);
            doc.roundedRect(x, y, cardWidth, cardHeight, 5).fillAndStroke(color, color);
            doc.font('Helvetica').fontSize(7.5).fillColor(COLORS.white)
                .text(label, x + 7, y + 9, { width: cardWidth - 14, align: 'center' });
            doc.font('Helvetica-Bold').fontSize(String(value).length > 7 ? 10 : 14)
                .fillColor(COLORS.white)
                .text(String(value), x + 7, y + 28, { width: cardWidth - 14, align: 'center' });
        });

        doc.y = y + cardHeight + 18;
    }

    static noteBox(doc, text, color) {
        this.ensureSpace(doc, 56);
        const top = doc.y;
        doc.roundedRect(PAGE.margin, top, this.contentWidth(doc), 48, 5)
            .fillAndStroke(COLORS.lightGray, COLORS.midGray);
        doc.font('Helvetica-Bold').fontSize(10).fillColor(color)
            .text(text, PAGE.margin + 14, top + 17, { width: this.contentWidth(doc) - 28 });
        doc.y = top + 64;
    }

    static inlineMeta(doc, rows) {
        rows.forEach(([label, value]) => {
            doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.gray).text(`${label}: `, { continued: true });
            doc.font('Helvetica').fontSize(9).fillColor(this.statusColor(value)).text(String(value || '-'));
        });
    }

    static inlineField(doc, label, value, y, color = COLORS.black) {
        const x = PAGE.margin + 14;
        const labelWidth = 108;
        const valueX = x + labelWidth;
        const valueWidth = this.contentWidth(doc) - labelWidth - 28;
        const text = String(value || '-');
        const valueHeight = doc.heightOfString(text, { width: valueWidth }) + 4;
        const height = Math.max(20, valueHeight);

        doc.font('Helvetica-Bold').fontSize(9).fillColor(COLORS.gray)
            .text(`${label}:`, x, y, { width: labelWidth });
        doc.font('Helvetica').fontSize(9).fillColor(color)
            .text(text, valueX, y, { width: valueWidth, height, ellipsis: true });

        return y + height + 2;
    }

    static image(doc, imagePath, options = {}) {
        const width = options.width || this.contentWidth(doc);
        const height = options.height || 280;
        const x = options.x || PAGE.margin;

        this.ensureSpace(doc, height + 24);
        const top = doc.y;

        doc.roundedRect(x, top, width, height, 4).stroke(COLORS.midGray);
        try {
            doc.image(imagePath, x + 8, top + 8, {
                fit: [width - 16, height - 16],
                align: 'center',
                valign: 'center'
            });
        } catch (error) {
            doc.font('Helvetica').fontSize(9).fillColor(COLORS.gray)
                .text(`Screenshot unavailable: ${path.basename(imagePath)}`, x + 10, top + 12, { width: width - 20 });
        }

        doc.y = top + height + 16;
    }

    static centerImage(doc, imagePath, width, height) {
        const x = (PAGE.width - width) / 2;
        const y = doc.y;

        try {
            doc.image(imagePath, x, y, {
                fit: [width, height],
                align: 'center',
                valign: 'center'
            });
            doc.y = y + height;
        } catch (error) {
            doc.font('Helvetica-Bold').fontSize(24).fillColor(COLORS.navy)
                .text(BRAND.name, PAGE.margin, y + 42, { width: this.contentWidth(doc), align: 'center' });
            doc.y = y + height;
        }
    }

    static sectionTitle(doc, text, options = {}) {
        this.ensureSpace(doc, 42);
        doc.font('Helvetica-Bold').fontSize(14).fillColor(COLORS.navy)
            .text(text, PAGE.margin, doc.y, {
                width: this.contentWidth(doc),
                align: options.align || 'left'
            });
        doc.moveDown(0.55);
    }

    static divider(doc) {
        doc.moveTo(PAGE.margin, doc.y)
            .lineTo(PAGE.width - PAGE.margin, doc.y)
            .lineWidth(0.8)
            .stroke(COLORS.midGray);
    }

    static footer(doc, totalPages = this.pageCount(doc)) {
        const range = doc.bufferedPageRange();
        const end = range.start + totalPages;
        for (let index = range.start; index < end; index += 1) {
            doc.switchToPage(index);

            const pageNumber = index + 1;
            const footerY = doc.page.height - doc.page.margins.bottom - 22;

            doc.moveTo(PAGE.margin, footerY - 10)
                .lineTo(PAGE.width - PAGE.margin, footerY - 10)
                .lineWidth(0.6)
                .stroke(COLORS.midGray);

            doc.font('Helvetica-Bold').fontSize(8).fillColor(COLORS.navy)
                .text(BRAND.name, PAGE.margin, footerY, {
                    width: 150,
                    align: 'left',
                    lineBreak: false
                });
            doc.font('Helvetica').fontSize(8).fillColor(COLORS.gray)
                .text(`Page ${pageNumber} of ${totalPages}`, PAGE.margin, footerY, {
                    width: this.contentWidth(doc),
                    align: 'center',
                    lineBreak: false
                });
            doc.text(BRAND.footer, PAGE.width - PAGE.margin - 210, footerY, {
                width: 210,
                align: 'right',
                lineBreak: false
            });
        }
    }

    static pageCount(doc) {
        return doc.bufferedPageRange().count;
    }

    static validatePageCount(doc, expectedPages) {
        const generatedPages = this.pageCount(doc);

        if (generatedPages !== expectedPages) {
            console.warn([
                'WARNING:',
                'Blank page generation detected',
                `Generated Pages: ${generatedPages}`,
                `Expected Pages: ${expectedPages}`
            ].join('\n'));
        }
    }

    static ensureSpace(doc, needed) {
        if (doc.y + needed > PAGE.height - PAGE.bottom) {
            doc.addPage();
        }
    }

    static logoPath(customPath) {
        const candidates = [
            customPath,
            path.join(process.cwd(), 'assets', 'heyna-logo.png')
        ].filter(Boolean);

        return candidates.find(candidate => fs.existsSync(candidate)) || null;
    }

    static resolveScreenshot(screenshot) {
        if (!screenshot) return null;
        const absolutePath = path.isAbsolute(screenshot)
            ? screenshot
            : path.join(process.cwd(), screenshot);
        return fs.existsSync(absolutePath) ? absolutePath : null;
    }

    static findLatestFailedScreenshot(testCase) {
        const folder = path.join(process.cwd(), 'evidence', testCase);
        if (!fs.existsSync(folder)) return null;

        const file = fs.readdirSync(folder)
            .filter(name => name.toLowerCase().endsWith('.png'))
            .sort()
            .reverse()
            .find(name => name.includes('FAILED'));

        return file ? path.join(folder, file) : null;
    }

    static contentWidth(doc) {
        return doc.page.width - (PAGE.margin * 2);
    }

    static normalizeStatus(status) {
        const value = String(status || '').toUpperCase();
        if (value === 'PASS') return 'PASSED';
        if (value === 'FAIL') return 'FAILED';
        if (value === 'SKIP') return 'SKIPPED';
        return value || 'UNKNOWN';
    }

    static statusColor(status) {
        const normalized = this.normalizeStatus(status);
        if (normalized === 'PASSED' || normalized === 'PASSED:') return COLORS.green;
        if (normalized === 'FAILED' || normalized === 'FAILED:') return COLORS.red;
        if (normalized === 'SKIPPED' || normalized === 'SKIPPED:') return COLORS.orange;
        return COLORS.black;
    }

    static formatDuration(ms) {
        const value = Number(ms || 0);
        if (value < 1000) return `${Math.round(value)}ms`;
        if (value < 60000) return `${(value / 1000).toFixed(2)}s`;

        const minutes = Math.floor(value / 60000);
        const seconds = ((value % 60000) / 1000).toFixed(1);
        return `${minutes}m ${seconds}s`;
    }
}

module.exports = HeynaPdfGenerator;
module.exports.HeynaPdfGenerator = HeynaPdfGenerator;
