const fs = require('fs');
const path = require('path');
const Heyna = require('./HeynaReporter');

const BRAND = {
    name: 'HEYNA REPORT',
    tagline: 'From Execution to Evidence.',
    subtitle: 'HTML Dashboard Foundation'
};

class HeynaHtmlDashboardGenerator {
    static async generate(options = {}) {
        const outputPath = options.outputPath || path.join(process.cwd(), 'dashboard', 'index.html');
        fs.mkdirSync(path.dirname(outputPath), { recursive: true });

        const metadata = Heyna.getMetadata();
        const summary = Heyna.getSummary();
        const executionData = Heyna.getExecutionData();
        const coverage = this.coverageData(metadata);
        const html = this.document({ metadata, summary, executionData, coverage });

        fs.writeFileSync(outputPath, html, 'utf8');
        return outputPath;
    }

    static document({ metadata, summary, executionData, coverage }) {
        const title = `${BRAND.name} Dashboard`;

        return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${this.escape(title)}</title>
  <style>${this.styles()}</style>
</head>
<body>
  <main class="dashboard-shell">
    ${this.header(metadata)}
    ${this.summaryCards(summary)}
    ${this.testCaseTable(executionData)}
    ${this.coverageDiagnostics(coverage)}
    ${this.recentFailedTests(executionData)}
    <footer class="dashboard-footer">Generated by ${this.escape(BRAND.name)} &middot; ${this.escape(new Date().toLocaleString())}</footer>
  </main>
</body>
</html>
`;
    }

    static header(metadata) {
        const items = [
            ['Project', metadata.project],
            ['Feature', metadata.feature],
            ['Environment', metadata.environment],
            ['Browser', metadata.browser],
            ['Tool', metadata.automationTool],
            ['Executed By', metadata.executedBy],
            ['Run Status', metadata.runStatus],
            ['Started', this.formatDate(metadata.executionStartTime)],
            ['Completed', this.formatDate(metadata.executionEndTime)]
        ];

        return `<header class="dashboard-header">
  <div>
    <p class="eyebrow">${this.escape(BRAND.subtitle)}</p>
    <h1>${this.escape(BRAND.name)}</h1>
    <p class="tagline">${this.escape(BRAND.tagline)}</p>
  </div>
  <dl class="metadata-grid">
    ${items.map(([label, value]) => `<div class="metadata-item"><dt>${this.escape(label)}</dt><dd>${this.escape(value || '-')}</dd></div>`).join('\n    ')}
  </dl>
</header>`;
    }

    static summaryCards(summary) {
        const cards = [
            ['Total Tests', summary.total, 'blue'],
            ['Passed', summary.passed, 'green'],
            ['Failed', summary.failed, 'red'],
            ['Skipped', summary.skipped, 'orange'],
            ['Pass Rate', `${summary.passRate}%`, 'navy'],
            ['Duration', this.formatDuration(summary.totalDuration), 'gray']
        ];

        return `<section class="panel" aria-labelledby="summary-heading">
  <div class="section-heading">
    <p class="eyebrow">Run Summary</p>
    <h2 id="summary-heading">Summary Cards</h2>
  </div>
  <div class="summary-grid">
    ${cards.map(([label, value, tone]) => `<article class="summary-card tone-${tone}"><span>${this.escape(label)}</span><strong>${this.escape(value)}</strong></article>`).join('\n    ')}
  </div>
</section>`;
    }

    static testCaseTable(executionData) {
        const rows = executionData.map(testCase => {
            const status = this.normalizeStatus(testCase.status);
            return `<tr>
      <td>${this.escape(testCase.testCase)}</td>
      <td>${this.escape(testCase.feature || '-')}</td>
      <td><span class="status ${this.statusClass(status)}">${this.escape(status)}</span></td>
      <td>${this.escape(this.formatDuration(testCase.duration))}</td>
      <td>${this.escape((testCase.steps || []).length)}</td>
      <td>${this.escape(testCase.retryCount || 0)}</td>
      <td>${this.escape(this.formatDate(testCase.executionDate))}</td>
    </tr>`;
        }).join('\n    ');

        return `<section class="panel" aria-labelledby="test-case-heading">
  <div class="section-heading">
    <p class="eyebrow">Execution Detail</p>
    <h2 id="test-case-heading">Test Case Table</h2>
  </div>
  ${executionData.length ? `<div class="table-wrap"><table>
    <thead><tr><th scope="col">Test Case</th><th scope="col">Feature</th><th scope="col">Status</th><th scope="col">Duration</th><th scope="col">Steps</th><th scope="col">Retries</th><th scope="col">Execution Date</th></tr></thead>
    <tbody>${rows}</tbody>
  </table></div>` : '<p class="empty-state">No test execution data found.</p>'}
</section>`;
    }

    static coverageDiagnostics(coverage) {
        if (!coverage) {
            return `<section class="panel" aria-labelledby="coverage-heading">
  <div class="section-heading">
    <p class="eyebrow">Diagnostics</p>
    <h2 id="coverage-heading">Coverage Diagnostics</h2>
  </div>
  <p class="empty-state">No auto-capture coverage data available.</p>
</section>`;
        }

        const rows = Object.entries(coverage.byAction || {}).sort(([a], [b]) => a.localeCompare(b)).map(([action, stats]) => {
            const detected = Number(stats.detected || 0);
            const captured = Number(stats.captured || 0);
            const missed = Math.max(0, detected - captured);
            const rate = detected ? `${((captured / detected) * 100).toFixed(2)}%` : '0.00%';
            return `<tr><td>${this.escape(action)}</td><td>${this.escape(detected)}</td><td>${this.escape(captured)}</td><td>${this.escape(missed)}</td><td>${this.escape(rate)}</td></tr>`;
        }).join('\n      ');

        return `<section class="panel" aria-labelledby="coverage-heading">
  <div class="section-heading">
    <p class="eyebrow">Diagnostics</p>
    <h2 id="coverage-heading">Coverage Diagnostics</h2>
  </div>
  <div class="summary-grid diagnostics-grid">
    <article class="summary-card tone-blue"><span>Detected</span><strong>${this.escape(coverage.detected)}</strong></article>
    <article class="summary-card tone-green"><span>Captured</span><strong>${this.escape(coverage.captured)}</strong></article>
    <article class="summary-card tone-red"><span>Missed</span><strong>${this.escape(coverage.missed)}</strong></article>
    <article class="summary-card tone-navy"><span>Capture Rate</span><strong>${this.escape(coverage.captureRate)}</strong></article>
  </div>
  ${rows ? `<div class="table-wrap"><table>
    <thead><tr><th scope="col">Action</th><th scope="col">Detected</th><th scope="col">Captured</th><th scope="col">Missed</th><th scope="col">Capture Rate</th></tr></thead>
    <tbody>${rows}</tbody>
  </table></div>` : '<p class="empty-state">No per-action diagnostics available.</p>'}
</section>`;
    }

    static recentFailedTests(executionData) {
        const failedTests = executionData
            .filter(testCase => this.normalizeStatus(testCase.status) === 'FAILED')
            .slice(-5)
            .reverse();

        return `<section class="panel" aria-labelledby="failed-heading">
  <div class="section-heading">
    <p class="eyebrow">Failure Focus</p>
    <h2 id="failed-heading">Recent Failed Tests</h2>
  </div>
  ${failedTests.length ? `<div class="failed-list">${failedTests.map(testCase => `<article class="failed-card"><strong>${this.escape(testCase.testCase)}</strong><p>${this.escape(testCase.errorMessage || 'No error message captured.')}</p></article>`).join('\n    ')}</div>` : '<p class="empty-state success">No failed tests found in this run.</p>'}
</section>`;
    }

    static coverageData(metadata) {
        const coverage = metadata.autoCaptureCoverage;
        if (!coverage) return null;

        const detected = Number(coverage.detected || 0);
        const captured = Number(coverage.captured || 0);
        const missed = Number(coverage.missed == null ? Math.max(0, detected - captured) : coverage.missed);
        const captureRate = detected ? `${((captured / detected) * 100).toFixed(2)}%` : '0.00%';

        return {
            detected,
            captured,
            missed,
            captureRate,
            byAction: coverage.byAction || {}
        };
    }

    static styles() {
        return `:root{--navy:#123A63;--navy-dark:#0B2A47;--green:#16A05D;--red:#D32F2F;--orange:#F59E0B;--blue:#2563EB;--black:#1F2937;--gray:#6B7280;--light:#F8FAFC;--border:#E5E7EB;--white:#FFFFFF}*{box-sizing:border-box}body{margin:0;background:linear-gradient(180deg,#eef5ff 0%,#f8fafc 40%,#fff 100%);color:var(--black);font-family:Inter,Segoe UI,Arial,sans-serif}.dashboard-shell{width:min(1180px,calc(100% - 32px));margin:0 auto;padding:32px 0}.dashboard-header{display:grid;grid-template-columns:minmax(260px,1fr) minmax(320px,1.4fr);gap:24px;align-items:stretch;background:var(--navy);color:var(--white);border-radius:22px;padding:30px;box-shadow:0 20px 45px rgba(18,58,99,.18)}h1{font-size:clamp(2rem,5vw,4rem);line-height:1;margin:8px 0}.tagline{color:#dbeafe;margin:0}.eyebrow{margin:0 0 6px;text-transform:uppercase;letter-spacing:.12em;font-size:.76rem;font-weight:700;color:#93c5fd}.metadata-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:0}.metadata-item{background:rgba(255,255,255,.11);border:1px solid rgba(255,255,255,.18);border-radius:14px;padding:12px}.metadata-item dt{font-size:.72rem;color:#bfdbfe;text-transform:uppercase;letter-spacing:.08em}.metadata-item dd{margin:5px 0 0;font-weight:700;overflow-wrap:anywhere}.panel{background:var(--white);border:1px solid var(--border);border-radius:20px;margin-top:22px;padding:24px;box-shadow:0 12px 30px rgba(15,23,42,.06)}.section-heading{display:flex;justify-content:space-between;gap:16px;align-items:end;margin-bottom:16px}.section-heading h2{margin:0;color:var(--navy);font-size:1.35rem}.summary-grid{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px}.summary-card{border:1px solid var(--border);border-left:5px solid var(--gray);border-radius:16px;padding:16px;background:var(--light)}.summary-card span{display:block;color:var(--gray);font-size:.8rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em}.summary-card strong{display:block;font-size:1.7rem;margin-top:8px;color:var(--black)}.tone-blue{border-left-color:var(--blue)}.tone-green{border-left-color:var(--green)}.tone-red{border-left-color:var(--red)}.tone-orange{border-left-color:var(--orange)}.tone-navy{border-left-color:var(--navy)}.tone-gray{border-left-color:var(--gray)}.table-wrap{overflow-x:auto;border:1px solid var(--border);border-radius:16px}table{width:100%;border-collapse:collapse;min-width:760px;background:var(--white)}th,td{text-align:left;padding:13px 14px;border-bottom:1px solid var(--border);vertical-align:top}th{background:var(--navy);color:var(--white);font-size:.78rem;text-transform:uppercase;letter-spacing:.06em}tbody tr:nth-child(even){background:var(--light)}tbody tr:last-child td{border-bottom:0}.status{display:inline-flex;align-items:center;border-radius:999px;padding:4px 10px;font-size:.76rem;font-weight:800}.status-passed{background:#dcfce7;color:#166534}.status-failed{background:#fee2e2;color:#991b1b}.status-skipped{background:#ffedd5;color:#9a3412}.status-running{background:#dbeafe;color:#1e40af}.status-unknown{background:#e5e7eb;color:#374151}.diagnostics-grid{grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:18px}.empty-state{margin:0;padding:18px;border:1px dashed var(--border);border-radius:14px;background:var(--light);color:var(--gray)}.empty-state.success{border-color:#bbf7d0;background:#f0fdf4;color:#166534}.failed-list{display:grid;gap:12px}.failed-card{border:1px solid #fecaca;background:#fff7f7;border-radius:14px;padding:14px}.failed-card strong{color:var(--red)}.failed-card p{margin:8px 0 0;color:var(--gray)}.dashboard-footer{text-align:center;color:var(--gray);font-size:.85rem;margin:26px 0 8px}@media (max-width:900px){.dashboard-header{grid-template-columns:1fr}.metadata-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.summary-grid,.diagnostics-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media (max-width:560px){.dashboard-shell{width:min(100% - 20px,1180px);padding:16px 0}.dashboard-header,.panel{padding:18px;border-radius:16px}.metadata-grid,.summary-grid,.diagnostics-grid{grid-template-columns:1fr}.section-heading{display:block}}`;
    }

    static escape(value) {
        return String(value == null ? '' : value)
            .replace(/&/g, '&amp;')
            .replace(/</g, '&lt;')
            .replace(/>/g, '&gt;')
            .replace(/"/g, '&quot;')
            .replace(/'/g, '&#39;');
    }

    static normalizeStatus(status) {
        const value = String(status || '').toUpperCase();
        if (value === 'PASS') return 'PASSED';
        if (value === 'FAIL' || value === 'TIMEDOUT' || value === 'INTERRUPTED') return 'FAILED';
        if (value === 'SKIP') return 'SKIPPED';
        return value || 'UNKNOWN';
    }

    static statusClass(status) {
        const normalized = this.normalizeStatus(status).toLowerCase();
        if (['passed', 'failed', 'skipped', 'running'].includes(normalized)) return `status-${normalized}`;
        return 'status-unknown';
    }

    static formatDuration(ms) {
        const value = Number(ms || 0);
        if (value < 1000) return `${Math.round(value)}ms`;
        if (value < 60000) return `${(value / 1000).toFixed(2)}s`;
        const minutes = Math.floor(value / 60000);
        const seconds = ((value % 60000) / 1000).toFixed(1);
        return `${minutes}m ${seconds}s`;
    }

    static formatDate(value) {
        if (!value) return '-';
        const date = new Date(value);
        return Number.isNaN(date.getTime()) ? value : date.toLocaleString();
    }
}

module.exports = HeynaHtmlDashboardGenerator;
module.exports.HeynaHtmlDashboardGenerator = HeynaHtmlDashboardGenerator;
